// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package sqs

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewSQSClient(queue *string) (*SQSClient, error) {
	sqsClient, err := newSQSClient(queue)
	if err != nil {
		return nil, err
	}
	return sqsClient, nil
}

// wire.go:

var SQSSet = wire.NewSet(
	newSQSClient, wire.Bind(new(SQSClientInterface), new(*SQSClient)),
)
