// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ssm

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitSSMClient() *SSMClient {
	ssmClient := NewSSMClient()
	return ssmClient
}

// wire.go:

var SSMSet = wire.NewSet(
	NewSSMClient, wire.Bind(new(SSMClientInterface), new(*SSMClient)),
)
